kanta = input("suorakulmion kannan pitus: ")
korkeus = input("suorakulmion korkeus: ")
piiri = str(int(kanta)*2 + int(korkeus)*2)
pin = str(int(kanta) * int(korkeus))
print("suorakulmion piiri on: " + piiri + "ja pinta-ala on: " + pin)
